spring.application.name=la-voute

# Database
spring.datasource.url=jdbc:mariadb://localhost:3306/lavoute
spring.datasource.username=lavoute
spring.datasource.password=lavoute
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
