spring.application.name=la-voute

spring.profiles.active=dev

logging.console.enabled=true

# Database
spring.datasource.url=jdbc:mariadb://localhost:3306/lavoute
spring.datasource.username=lavoute
spring.datasource.password=lavoute
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# File upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
hashids.salt=AJDI840LSUDNfh83cbnSBF6
storage.root=storage

# File sharing
app.signed-url.duration-minutes=5
app.signed-url.secret=yEDfhjt/9K2qHchx+xx+KltwnrGyd1mhTT4tJdWcWU0=

# TRES IMPORTANT VOUS TOUCHEZ A QUELQUE CHOSE ICI JE VOUS TUE (en prod, en dev c'est moins grave) -- SAMUEL
# A commenter si les logs deviennent dure a lire
# Montre le sql generer et utiliser par hibernate
#spring.jpa.show-sql=true

# Montre les logs de Flyway
#logging.level.org.flywaydb=DEBUG

# TRES IMPORTANT VOUS TOUCHEZ A QUELQUE CHOSE ICI JE VOUS TUE (en prod, en dev c'est moins grave) -- SAMUEL
# IMPORTANT Decommenter et runner l'app pour verifier que les models match avec les tables dans la bd
spring.jpa.hibernate.ddl-auto=validate

# IMPORTANT (Dev seulement) Drop toute la bd et recreer les tables
#spring.jpa.hibernate.ddl-auto=create

# IMPORTANT Garde la bd et ajoute les changements
#spring.jpa.hibernate.ddl-auto=update


