spring.application.name=la-voute

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# File upload
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}
hashids.salt=${HASHIDS_SALT}
hashids.download.salt=${HASHIDS_DOWNLOAD_SALT}
storage.root=${STORAGE_ROOT}

# Cloudflare Turnstile
turnstile.secret=${TURNSTILE_SECRET_KEY}

# File sharing
app.signed-url.duration-minutes=5
app.signed-url.secret=yEDfhjt/9K2qHchx+xx+KltwnrGyd1mhTT4tJdWcWU0=

# TRES IMPORTANT VOUS TOUCHEZ A QUELQUE CHOSE ICI JE VOUS TUE (en prod, en dev c'est moins grave) -- SAMUEL
# A commenter si les logs deviennent dure a lire
# Montre le sql generer et utiliser par hibernate
#spring.jpa.show-sql=true

# Montre les logs de Flyway
#logging.level.org.flywaydb=DEBUG

# TRES IMPORTANT VOUS TOUCHEZ A QUELQUE CHOSE ICI JE VOUS TUE (en prod, en dev c'est moins grave) -- SAMUEL
# IMPORTANT Decommenter et runner l'app pour verifier que les models match avec les tables dans la bd
spring.jpa.hibernate.ddl-auto=validate

# IMPORTANT (Dev seulement) Drop toute la bd et recreer les tables
#spring.jpa.hibernate.ddl-auto=create

# IMPORTANT Garde la bd et ajoute les changements
#spring.jpa.hibernate.ddl-auto=update


